# Generated by Django 5.2.4 on 2026-05-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_supplier_delete_distributor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['supplier_id']},
        ),
    ]
